schema_version: 1

context:
  name: pmdarima
  version: "2.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: b8d2a0c0cd3f7ec90825fa25a917b5f66073de58033511de015a9e76e4e3d8f7

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy >=2.0.0
        - cython >=0.29,!=0.29.18,!=0.29.31
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - meson-python >=0.15.0
    - numpy >=2.0.0
    - cython >=0.29,!=0.29.18,!=0.29.31
    - pip
  run:
    - python
    - joblib >=0.11
    - cython >=0.29,!=0.29.18,!=0.29.31
    - pandas >=0.19
    - scikit-learn >=0.22
    - scipy >=1.13.0
    - statsmodels >=0.14.5
    - urllib3
    - setuptools >=42,!=50.0.0
    - packaging >=17.1

tests:
  - python:
      imports:
        - pmdarima
      pip_check: true

about:
  license: MIT
  license_file: LICENSE
  summary: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities
  homepage: https://github.com/alkaline-ml/pmdarima

extra:
  recipe-maintainers:
    - tomasvanpottelbergh
    - cdesouza21
    - mgorny
